Create UniqueBST.java
Jiganesh/Loads-Of-Logic pull request #312
Opened 2022-10-15 07:34 UTC by AbhishekJha45

added dp solution of uniqueBST

2022-10-15 07:39 UTC, Jiganesh requested changes
file name should be in pascal case
example if problem name is Unique Binary Search Tree

filename = uniqueBinarySearchTree.java

2022-10-15 07:39 UTC, Jiganesh commented on dynamicProgramming/UniqueBST.java
> +public long nthCatalan(int n) {
Please add problem link at top line 
Please include package dynamicProgramming ;

2022-10-15 08:28 UTC, AbhishekJha45 commented on dynamicProgramming/UniqueBST.java
> +public long nthCatalan(int n) {
ok

2022-10-16 07:56 UTC, Jiganesh approved these changes

2022-10-16 07:56 UTC, merged